general:
  debug: true

telegram:
  token: "****"

postgres:
  database: "bot-template"
  username: "bot-template"
  password: "super_secure_password"
  host: "localhost"
  port: "5432"
  sslmode: "disable"
